[package]
name = "hack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuser = "0.14.0"
lazy_static = "1.4.0"
libc = "0.2.154"
